name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

#permissions:
#  contents: write

jobs:
  exec_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run commands
        run: |
          echo ok
          ls
